/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhtar
 */
public class v_forward extends javax.swing.JFrame {

    /**
     * Creates new form v_forward
     */
    public v_forward() {
        initComponents();
    }

    public JTextField getHasil() {
        return hasil;
    }

//    public String getHasil() {
//        return hasil.getText();
//    }
//    public void setHasil(String hasil) {
//        this.hasil.setText(hasil);
//    }
    

    public int getcIdbobot() {
        return idbobot.getSelectedIndex();
    }

    public JComboBox<String> getIdbobot() {
        return idbobot;
    }

    public void check(ItemListener a) {
        this.idbobot.addItemListener(a);
    }

    public void setIdbobot(String[] idbobot) {
        for (String a : idbobot) {
            this.idbobot.addItem(a);
        }
    }

    public void setIdbobot(int idbobot) {
        this.idbobot.setSelectedIndex(idbobot);
    }

    public int getcBobotb() {
        return bobotb.getSelectedIndex();
    }

    public JComboBox<String> getBobotb() {
        return bobotb;
    }

    public void combo(ItemListener a) {
        this.bobotb.addItemListener(a);
    }

    public void setBobotb(String[] bobotb) {
        for (String a : bobotb) {
            this.bobotb.addItem(a);
        }
    }

    public void setBobot(int bobotb) {
        this.bobotb.setSelectedIndex(bobotb);
    }

    public int getcAturan() {
        return aturan.getSelectedIndex();
    }

    public JComboBox<String> getAturan() {
        return aturan;
    }

    public void box(ItemListener a) {
        this.aturan.addItemListener(a);
    }

    public void setAturan(String[] aturan) {
        for (String a : aturan) {
            this.aturan.addItem(a);
        }
    }

    public void setaturan(int aturan) {
        this.aturan.setSelectedIndex(aturan);
    }

    public JTextField getAbobot() {
        return abobot;
    }

    public JTextField getBbobot() {
        return bbobot;
    }

    public JTextField getHaturan() {
        return haturan;
    }
    
    

//    public String getAbobot() {
//        return abobot.getText();
//    }
//
    public void setAbobot(String abobot) {
        this.abobot.setText(abobot);
    }
//
//    public String getBbobot() {
//        return bbobot.getText();
//    }
//
    public void setBbobot(String bbobot) {
        this.bbobot.setText(bbobot);
    }
//
//    public String getHaturan() {
//        return haturan.getText();
//    }
    
    
//
    public void setHaturan(String haturan) {
        this.haturan.setText(haturan);
    }

    public int getSelectedRow() {
        return table.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.table.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.table.getValueAt(baris, kolom);
    }

    public void addHitungListener(ActionListener listener) {
        hitung.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idbobot = new javax.swing.JComboBox<>();
        bobotb = new javax.swing.JComboBox<>();
        aturan = new javax.swing.JComboBox<>();
        hasil = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        abobot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bbobot = new javax.swing.JTextField();
        haturan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idbobot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(idbobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 45, 60, -1));

        bobotb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(bobotb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, -1));

        aturan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(aturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, -1));

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, -1));

        hitung.setText("Hitung");
        getContentPane().add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 20));
        getContentPane().add(abobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 290, 160));
        getContentPane().add(bbobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 160, 160, -1));
        getContentPane().add(haturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_forward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_forward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_forward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_forward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_forward().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abobot;
    private javax.swing.JComboBox<String> aturan;
    private javax.swing.JTextField bbobot;
    private javax.swing.JComboBox<String> bobotb;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField haturan;
    private javax.swing.JButton hitung;
    private javax.swing.JComboBox<String> idbobot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
